//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS_REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyOrder
    {
        public int Order_ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Student_id { get; set; }
        public int Stock_id { get; set; }
        public Nullable<double> Stock_Price { get; set; }
        public int Quantity { get; set; }
        public string Function { get; set; }
        public string Type { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual Student Student { get; set; }
    }
}
