//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS_REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int id { get; set; }
        public int Student_ID { get; set; }
        public int Stocks_ID { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
